DATASET:
  class_names: null
  norms: null

TRAIN:
  # image and model directories
  train_dir: null
  additional_train_dirs: null

  model_dir: "empanada_models"
  save_freq: 1

  finetune_layer: null

  # set the lr schedule
  lr_schedule: "OneCycleLR"
  schedule_params:
    max_lr: 0.003
    epochs: 30
    steps_per_epoch: -1
    pct_start: 0.3

  # setup the optimizer
  amp: True
  optimizer: "AdamW"
  optimizer_params:
    weight_decay: 0.1

  # performance metrics
  print_freq: 1
  metrics:
      - { metric: "IoU", name: "semantic_iou", labels: [ 1 ], output_key: "sem_logits",  target_key: "sem"}

  # dataset parameters
  batch_size: 16
  workers: 0

  dataset_class: null
  dataset_params:
      weight_gamma: 0.0

  augmentations:
    - { aug: "RandomScale", scale_limit: [ -0.9, 1 ]}
    - { aug: "PadIfNeeded", min_height: 256, min_width: 256, border_mode: 0 }
    - { aug: "RandomCrop", height: 256, width: 256}
    - { aug: "Rotate", limit: 180, border_mode: 0 }
    - { aug: "RandomBrightnessContrast", brightness_limit: 0.3, contrast_limit: 0.3 }
    - { aug: "HorizontalFlip" }
    - { aug: "VerticalFlip" }
